<a href="https://colab.research.google.com/github/25wh1a0547-ux/NASSCOM/blob/main/NumPy_Exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

print("--- Intermediate NumPy Exercise ---")
print("Complete each task by writing the requested NumPy code.")
print("-----------------------------------")

# Task 1: Array Creation Shortcuts
print("\n--- Task 1: Array Creation Shortcuts ---")

# 1.1
arr1_1 = np.arange(0, 100)

# 1.2

# 1.3
arr1_3 = np.full((2, 4), 7)

# 1.4
arr1_4 = np.random.randint(10, 51, size=(5, 5))

print("arr1_1 (first 10 elements):", arr1_1[:10])
print("arr1_2:\n", arr1_2)
print("arr1_3:\n", arr1_3)
print("arr1_4 (first 2 rows):\n", arr1_4[:2])


--- Intermediate NumPy Exercise ---
Complete each task by writing the requested NumPy code.
-----------------------------------

--- Task 1: Array Creation Shortcuts ---
arr1_1 (first 10 elements): [0 1 2 3 4 5 6 7 8 9]
arr1_2:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
arr1_3:
 [[7 7 7 7]
 [7 7 7 7]]
arr1_4 (first 2 rows):
 [[25 20 31 47 15]
 [44 29 34 17 30]]


In [5]:
data = np.array([[10, 20, 30, 40],
                 [50, 60, 70, 80],
                 [90, 100, 110, 120],
                 [130, 140, 150, 160]])
# 2.1
val2_1 = data[2, 3]

# 2.2
row2_2 = data[0, :]

# 2.3
col2_3 = data[:, 3]

# 2.4
sub_arr2_4 = data[1:3, 0:2]

# 2.5
filtered_elements2_5 = data[data > 100]

print("val2_1:", val2_1)
print("row2_2:", row2_2)
print("col2_3:", col2_3)
print("sub_arr2_4:\n", sub_arr2_4)
print("filtered_elements2_5:", filtered_elements2_5)

val2_1: 120
row2_2: [10 20 30 40]
col2_3: [ 40  80 120 160]
sub_arr2_4:
 [[ 50  60]
 [ 90 100]]
filtered_elements2_5: [110 120 130 140 150 160]


In [8]:
arr3_1 = np.random.randint(1, 21, size=(4, 5))
# 3.1
arr3_2 = np.where(arr3_1 < 10, 0, arr3_1)

# 3.2
even_count3_3 = np.count_nonzero(arr3_1 % 2 == 0)

print("arr3_1:\n", arr3_1)
print("arr3_2:\n", arr3_2)
print("even_count3_3:", even_count3_3)

arr3_1:
 [[11  9 16 18 19]
 [13  6 12 11 13]
 [18 12  7 13  5]
 [ 7 16  9  2 20]]
arr3_2:
 [[11  0 16 18 19]
 [13  0 12 11 13]
 [18 12  0 13  0]
 [ 0 16  0  0 20]]
even_count3_3: 9


In [9]:
arr4_1 = np.array([[10, 5, 12],
                   [3, 8, 15],
                   [20, 7, 4]])

# 4.1
sum4_1 = np.sum(arr4_1)

# 4.2
mean_cols4_2 = np.mean(arr4_1, axis=0)

# 4.3
max_rows4_3 = np.max(arr4_1, axis=1)

# 4.4
std4_4 = np.std(arr4_1)

print("sum4_1:", sum4_1)
print("mean_cols4_2:", mean_cols4_2)
print("max_rows4_3:", max_rows4_3)
print("std4_4:", std4_4)

sum4_1: 84
mean_cols4_2: [11.          6.66666667 10.33333333]
max_rows4_3: [12 15 20]
std4_4: 5.2493385826745405


In [10]:
print("\n--- Task 5: Reshaping and Flattening ---")
arr5_1 = np.arange(24)
# 5.1
reshaped_arr5_2 = arr5_1.reshape(4, 6)

# 5.2
reshaped_arr5_3 = arr5_1.reshape(2, 3, 4)
# 5.3
flattened_arr5_4 = reshaped_arr5_2.ravel()
flattened_arr5_4_copy = reshaped_arr5_2.flatten()

print("reshaped_arr5_2:\n", reshaped_arr5_2)
print("\nreshaped_arr5_3:\n", reshaped_arr5_3)
print("\nflattened_arr5_4 (ravel):\n", flattened_arr5_4)
print("\nflattened_arr5_4_copy (flatten):\n", flattened_arr5_4_copy)


--- Task 5: Reshaping and Flattening ---
reshaped_arr5_2:
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]

reshaped_arr5_3:
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

flattened_arr5_4 (ravel):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]

flattened_arr5_4_copy (flatten):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [11]:
# Task 6: Broadcasting
print("\n--- Task 6: Broadcasting ---")
arr6_1 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
scalar = 10
vector = np.array([100, 200, 300])

# 6.1
result6_1 = arr6_1 + scalar

# 6.2
result6_2 = arr6_1 + vector

print("Result 6.1:\n", result6_1)
print("\nResult 6.2:\n", result6_2)


--- Task 6: Broadcasting ---
Result 6.1:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Result 6.2:
 [[101 202 303]
 [104 205 306]
 [107 208 309]]


In [12]:
# Task 7: Copying vs. Viewing Arrays
print("\n--- Task 7: Copying vs. Viewing Arrays ---")
original_arr7 = np.array([1, 2, 3, 4, 5])

# 7.1
view_arr7 = original_arr7[:]
view_arr7[0] = 99

print("Original array after modifying view:", original_arr7)
print("View array:", view_arr7)

# 7.2
copy_arr7 = original_arr7.copy()
copy_arr7[-1] = 0

print("Original array after modifying copy:", original_arr7)
print("Copy array:", copy_arr7)


--- Task 7: Copying vs. Viewing Arrays ---
Original array after modifying view: [99  2  3  4  5]
View array: [99  2  3  4  5]
Original array after modifying copy: [99  2  3  4  5]
Copy array: [99  2  3  4  0]


In [14]:
import numpy as np

# Task 8: Stacking and Splitting Arrays
print("\n--- Task 8: Stacking and Splitting Arrays ---")

arr8_a = np.array([[1, 2],
                   [3, 4]])

arr8_b = np.array([[5, 6],
                   [7, 8]])

arr8_c = np.array([[9, 10]])

# 8.1
vstack_arr8_1 = np.vstack((arr8_a, arr8_b))

# 8.2
hstack_arr8_2 = np.hstack((arr8_a, arr8_b))

# 8.3
combined_arr8_3 = np.vstack((vstack_arr8_1, arr8_c))

# 8.4
part1, part2, part3 = np.array_split(combined_arr8_3, 3)


print("Vertical Stack:")
print(vstack_arr8_1)

print("\nHorizontal Stack:")
print(hstack_arr8_2)

print("\nCombined Array:")
print(combined_arr8_3)

print("\nPart 1:")
print(part1)

print("\nPart 2:")
print(part2)

print("\nPart 3:")
print(part3)


--- Task 8: Stacking and Splitting Arrays ---
Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]

Combined Array:
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]

Part 1:
[[1 2]
 [3 4]]

Part 2:
[[5 6]
 [7 8]]

Part 3:
[[ 9 10]]


In [15]:
import numpy as np


print("\n--- Task 9: Sorting and Searching ---")

arr9_1 = np.array([5, 2, 8, 1, 9, 4, 7, 3, 6])

arr9_2d = np.array([[30, 20, 10],
                    [60, 50, 40],
                    [90, 80, 70]])

# 9.1
sorted_arr9_1 = np.sort(arr9_1)

# 9.2
sorted_cols9_2 = np.sort(arr9_2d, axis=0)

# 9.3
idx9_3 = np.where(arr9_1 == 9)

# 9.4
max_idx9_4 = np.argmax(arr9_1)


print("Sorted arr9_1:")
print(sorted_arr9_1)

print("\nSorted columns of arr9_2d:")
print(sorted_cols9_2)

print("\nIndex where value 9 is present:")
print(idx9_3)

print("\nIndex of maximum value:")
print(max_idx9_4)


--- Task 9: Sorting and Searching ---
Sorted arr9_1:
[1 2 3 4 5 6 7 8 9]

Sorted columns of arr9_2d:
[[30 20 10]
 [60 50 40]
 [90 80 70]]

Index where value 9 is present:
(array([4]),)

Index of maximum value:
4
